version: '3.4'

services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - PROD=1
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10
  
  db-staging:
    image: mariadb:10.7
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - PROD=0
    volumes:
      - ./db_staging_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10

  backend:
    image: finnharbeke/finnance:backend
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - CSRF_SESSION_KEY
      - SECRET_COOKIE_KEY
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
  
  backend-staging:
    image: finnharbeke/finnance:backend-staging
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - CSRF_SESSION_KEY
      - SECRET_COOKIE_KEY
    build:
      context: .
    depends_on:
      db-staging:
        condition: service_healthy

  finnance-build:
    image: finnharbeke/finnance:frontend
    build:
      context: ./frontend
    volumes:
      - ./build-production:/build/build

  build-staging:
    image: finnharbeke/finnance:frontend-staging
    build:
      context: ./frontend
    volumes:
      - ./build-staging:/build/build

  frontend:
    image: finnharbeke/finnance:nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./build-production:/usr/www/finnance
      - ./build-staging:/usr/www/finnance-staging
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
  
    
