version: '3.4'

services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      .env
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      # mysqladmin ping -h localhost -u root -p$MARIADB_ROOT_PASSWORD
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10

  backend:
    env_file:
      .env
    build:
      context: .
    ports:
      - 5050:5050
    depends_on:
      db:
        condition: service_healthy
        

  frontend:
    env_file:
      .env
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
  
    
