version: '3.4'

services:
  finnance-db:
    image: mariadb:10.7
    env_file:
      - .env
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      timeout: 1s
      retries: 30
  
  finnance-sdb:
    image: mariadb:10.7
    env_file:
      - .env
    restart: always
    volumes:
      - ./db_staging_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      timeout: 1s
      retries: 30

  finnance-backend:
    image: finnharbeke/finnance:backend
    env_file:
      - .env
    environment:
      - DB_HOST=finnance-db
    restart: always
    depends_on:
      finnance-db:
        condition: service_healthy
  
  finnance-sbackend:
    image: finnharbeke/finnance:backend-staging
    env_file:
      - .env
    environment:
      - DB_HOST=finnance-sdb
    restart: always
    depends_on:
      finnance-sdb:
        condition: service_healthy

  finnance-frontend:
    image: finnharbeke/finnance:frontend
    restart: always
    environment:
      - API_HOST=finnance-backend
    depends_on:
      - finnance-backend

  finnance-sfrontend:
    image: finnharbeke/finnance:frontend-staging
    restart: always
    environment:
      - API_HOST=finnance-sbackend
    depends_on:
      - finnance-sbackend

networks:
  pi:
  
    
