version: '3.4'

services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      .env
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - 3306

  backend:
    image: backend
    build:
      context: .
    ports:
      - 5050:5050
    depends_on:
      - db
