version: '3.4'

services:
  db:
    image: mariadb:10.7
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10
  
  db-staging:
    image: mariadb:10.7
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
    restart: always
    volumes:
      - ./db_staging_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10

  backend:
    image: finnharbeke/finnance:backend
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - CSRF_SESSION_KEY
      - SECRET_COOKIE_KEY
      - PROD=1
    restart: always
    depends_on:
      db:
        condition: service_healthy
  
  backend-staging:
    image: finnharbeke/finnance:backend-staging
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - CSRF_SESSION_KEY
      - SECRET_COOKIE_KEY
      - PROD=0
    restart: always
    depends_on:
      db-staging:
        condition: service_healthy

  frontend:
    image: finnharbeke/finnance:frontend
    volumes:
      - production:/build/volume

  frontend-staging:
    image: finnharbeke/finnance:frontend-staging
    volumes:
      - staging:/build/volume

  nginx:
    image: finnharbeke/finnance:nginx
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - production:/usr/www/finnance
      - staging:/usr/www/finnance-staging
    ports:
      - 80:80
      - 443:443
    depends_on:
      backend:
        condition: service_started
      backend-staging:
        condition: service_started
      build-production:
        condition: service_completed_successfully
      build-staging:
        condition: service_completed_successfully

volumes:
  production:
  staging:
  
    
