name: finnance
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - flask
  - flask-sqlalchemy
  - flask-login
  - flask-bcrypt
  - flask-cors
  - jsonschema
  - python-dateutil
  - gunicorn
  - pip:
    - mariadb==1.0.*
