name: deploy on server

on:
  workflow_run:
    workflows: [
      "production backend",
      "production frontend",
      "staging backend",
      "staging frontend",
    ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production
    steps:
      - name: ssh to deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ~/finnance
            wget https://raw.githubusercontent.com/finnharbeke/finnance/main/docker-compose.yml -O docker-compose.yml
            docker compose pull
            docker compose up -d --no-deps
            docker system prune --force --all
          host: ${{ secrets.HOST }}
          username: pi
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
