name: nginx

on:
  push:
    branches:
      - main
    paths:
      - 'nginx/**'
      - '.github/workflows/nginx.yml'

jobs:
  nginx:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: nginx
        uses: docker/build-push-action@v3
        with:
          context: ./nginx
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/finnance:nginx