name: staging frontend

on:
  push:
    branches:
      - staging
    paths:
      - 'frontend/**'
      - '.github/workflows/staging-frontend.yml'

jobs:
  staging-frontend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: docker-build-push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          platforms: linux/arm64
          tags: ${{ vars.DOCKERHUB_USERNAME }}/finnance:frontend-staging
          cache-to: type=inline